# Generated by Django 4.2.7 on 2025-09-06 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('target_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('type', models.CharField(choices=[('price_above', 'Price Above'), ('price_below', 'Price Below')], max_length=20)),
                ('enabled', models.BooleanField(default=True)),
                ('triggered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('triggered_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
