# Generated by Django 4.2.7 on 2025-09-08 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_alert_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='user',
        ),
    ]
