# Generated by Django 4.2.7 on 2025-08-31 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='stock',
            name='current_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
