# Generated by Django 4.2.7 on 2025-09-09 17:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portfolio', '0004_interestedstock'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='interestedstock',
            unique_together={('user', 'symbol')},
        ),
    ]
